site_name: ペパカレ Android
site_description: ペパカレ Android のカリキュラム用にテキストを置いたり課題を提出してもらうリポジトリです。
site_author: GMO Pepabo, Inc.
repo_name: pepabo/pepabo-college-android
repo_url: https://git.pepabo.com/pepabo/pepabo-college-android
nav:
- ホーム: index.md
- オブジェクト指向プログラミング:
  - オブジェクト指向プログラミングとは: oop/object_oriented_programing.md
theme:
  name: material
  language: ja
  logo: img/android.png
  favicon: img/favicon.svg
  palette:
    - scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - navigation.top
    - toc.integrate
    - header.autohide
plugins:
  - search:
      lang: ja
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
