site_name: ペパカレ Android
site_description: ペパカレ Android のカリキュラム用にテキストを置いたり課題を提出してもらうリポジトリです。
site_author: GMO Pepabo, Inc.
nav:
- ホーム: index.md
- オブジェクト指向プログラミング:
  - オブジェクト指向プログラミングとは: oop/object_oriented_programing.md
theme:
  name: material
  language: ja
  logo: img/android.png
  favicon: img/favicon.svg
  palette:
    scheme: default
    primary: blue
    accent: orange
  features:
    - tabs
plugins:
  - search:
      lang: ja
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
