site_name: Android App Study
site_description: これから Android アプリ開発をする人向けのハンズオンをまとめています。
site_author: tick-taku
repo_name: tick-taku/AndroidAppStudy
repo_url: https://github.com/tick-taku/AndroidAppStudy
nav:
- ホーム: index.md
- 環境構築:
  - Java のセットアップ: env/java_environment.md
- オブジェクト指向プログラミング:
  - オブジェクト指向プログラミングとは: oop/object_oriented_programing.md
  - Java で動かしてみよう: oop/java_foundation.md
theme:
  name: material
  language: ja
  logo: img/android.png
  favicon: img/favicon.svg
  palette:
    - scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - navigation.top
    - toc.integrate
    - header.autohide
plugins:
  - search:
      lang: ja
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
