site_name: ペパカレ Android
site_description: ペパカレ Android のカリキュラム用にテキストを置いたり課題を提出してもらうリポジトリです。
site_author: GMO Pepabo, Inc.
theme:
  name: material
  language: ja
  logo: android.png
  favicon: android.png
  palette:
    scheme: default
    primary: blue
    accent: orange
  features:
    - tabs
plugins:
  - search:
      lang: ja
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.magiclink
