name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: normal
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material pyyaml
      - name: Build MkDocs
        run: mkdocs build --verbose --clean --strict
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
